//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.04.28 at 08:46:57 PM CEST 
//


package hr.algebra.iisCoreBackend.soap;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the hr.algebra.iisCoreBackend.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: hr.algebra.iisCoreBackend.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetColorRequest }
     * 
     */
    public GetColorRequest createGetColorRequest() {
        return new GetColorRequest();
    }

    /**
     * Create an instance of {@link GetColorResponse }
     * 
     */
    public GetColorResponse createGetColorResponse() {
        return new GetColorResponse();
    }

}
