//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.09 at 10:53:23 AM CET 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://algebra.hr/iisbackend/soap", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package hr.algebra.iisCoreBackend.soap;
