spring.application.name=IIS-Backend

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.burlqxevioqdjttvaxqd
spring.datasource.password=Bg6w8V&cY8grL9E
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.keepalive-time=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.contentnegotiation.favor-parameter=false

app.reqres.api.key=reqres_7d2480b3336345d49186b7b672d6f699

# This is a default fallback secret for testing/production only
jwt.secret=dummy-key-prod-only
jwt.access-expiration=900000
jwt.refresh-expiration=86400000

## To use for testing the access and refresh functionality
## (1 minute)
#jwt.access-expiration=60000
#
## (3 minutes)
#jwt.refresh-expiration=180000

spring.graphql.graphiql.enabled=true
spring.graphql.http.path=/graphql

logging.level.org.springframework.security=TRACE