spring.application.name=IIS-Backend

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.burlqxevioqdjttvaxqd
spring.datasource.password=Bg6w8V&cY8grL9E
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.keepalive-time=30000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.contentnegotiation.favor-parameter=false

app.reqres.api.key=reqres_7d2480b3336345d49186b7b672d6f699

jwt.secret=46Q5WJB8xds1dMHtiHZUyXmBoh46wPug6qckJPV5uNn
jwt.access-expiration=900000
jwt.refresh-expiration=86400000

spring.graphql.graphiql.enabled=true
spring.graphql.http.path=/graphql

logging.level.org.springframework.security=TRACE